/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sdegaonk' at '7/27/16 10:21 AM' with Gradle 2.14.1
 *
 * @author sdegaonk, @date 7/27/16 10:21 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
